title: Network Modeling, Learning and Analysis (NMLA)
description: WorldCIST2020 Workshop
url: 'https://NMLA-WorldCIST.github.io/'
author: Sandra Mitrovic
email: NMLA-WorldCIST@gmail.com
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
