title: Network Modeling, Learning and Analysis (NMLA)
description: Network Modeling, Learning and Analysis Workshop @ WorldCIST2020
url: 'https://NMLA-WorldCIST.github.io/'
author: Sandra Mitrovic
email: NMLA-WorldCIST@gmail.com
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
