title: Network Modeling, Learning and Analysis (NMLA)
description: WorldCIST2020 Workshop (Budva, Montenegro)
url: 'https://NMLA-WorldCIST.github.io/'
author: Sandra Mitrovic
email: NMLA-WorldCIST@gmail.com
show_downloads: true
background-image: https://github.com/NMLA-WorldCIST/NMLA-WorldCIST.github.io/blob/master/images/Becici-Budva.jpg
google_analytics: 'UA-148963558-1'
theme: jekyll-theme-cayman
